language: node_js
node_js: node
services: 
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: nvuFMrT2nKYdPSibPYsrWgLIAncAgTjzqww70NberjaJK/RuvwBlCa+W1wMdZOXRzMOahuxGsTcW2kKGxhA1kHi8JtKmInjCC+8eO7Hl8/IvBOvLTKpwaDVo6iN3lckpjUNMVa7xnOlkLs5S1aUrl+x3c5iojWTddmMG5eMkD801WDqi7WP8ibmPcWWT9rz5ruWqs8zFspHG9aeYaYQj2t4oKjb5tpf+9bFXLwanf2bvPju8CMlkp8PCWJ1tDAozucVLKZdUZEeNcp8MuFIP+CV/M4e57L/rbFp4ZZX2zHxGGP/VMnXdz/iYG6L1yiCRXs0tByXFga7uhqYWuVyHdW8WAJFo1ZrmN/3A7X/CBAds3HCMCYD26gySxxWpJTspPfa+u3ByjnHzcr8/0U7mTsk7qoswgnkrnmDD3XcyeaK/3rM20+jaK/zbgneY0sp3bIPW6O+mekaYX/Z+o4HiqsYDNlnhY32JN1Wx6EzYnBCbw/EsVC5YcRFdheDZo1Dc0Cxb357GMo5febtCYxDNDL2jeiQpu7vfXmZxrh3V40st2tLdpexkafi9w+zeySCeNeCsvi8HbnrKxanSv4hNuYlI9ZHl9wxZUZ6KSfBH36fMHF4hDEUJka/nA2HNM4OptmDZ8CNDjtxefyXsUR2+us1f8Sdhakpcw1Hr5wf+vtA=
  app: thegoodnightapp
  on:
    repo: rachelekm/GoodnightApp
